# @HostAddress=https://localhost:4003
@HostAddress=https://localhost:10001
@AccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YTJkYWEzOC1jMDdiLTQ3NWYtYmQxZi04YzlkZDgwMTEwZGEiLCJnaXZlbl9uYW1lIjoiSHViZXJ0IiwiZmFtaWx5X25hbWUiOiJEdW1hcyIsImp0aSI6IjlmZGU2OGIwLTE5M2ItNDU0NS1iNDQ0LTdjOWU2ZDAwM2M3YyIsImN1c3RvbWVyX2lkIjoiMjI0OTI2MmItNjY0MS00YTI4LWI1NzgtMzc0NzAxMDY2Mjc0IiwiZXhwIjoxNzU5OTU5ODE1LCJpc3MiOiJodHRwczovL2dlbWluaW9wcy5jb20uYXUiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.ctQUv1Ef3SQ8YaFslpib_7vO1rz546HT3T9PKvE0GN4

GET {{HostAddress}}/orders?pageNumber=2&pageSize=5

###
GET {{HostAddress}}/orders?pageNumber=2&pageSize=5
Authorization: Bearer {{AccessToken}}

###

POST {{HostAddress}}/orders
Content-Type: application/json

{
  "customerId": "ac2a7b8c-b733-4a3a-850e-039045009288",
  "firstName": "John",
  "lastName": "Citizen",
  "email": "john.citizen@example.com",
  "currency": "AUD",
  "shippingAddress": {
    "addressLine1": "123 Main St",
    "addressLine2": "Apt 4B",
    "city": "Sydney",
    "state": "NSW",
    "postCode": "2000",
    "country": "Australia"
  },
  "Items": [
    {
      "productId": "00d5d543-71a1-4149-ae8b-6695a38d448c",
      "quantity": 2,
      "unitPrice": 89.99
    },
    {
      "productId": "1a308cf3-2bea-45cd-9575-c396db342ad3",
      "quantity": 1,
      "unitPrice": 149.99
    },
    {
      "productId": "e2416012-7ad8-431a-9372-24cca3519c2b",
      "quantity": 100,
      "unitPrice": 329.99
    }
  ]
}

###

POST {{HostAddress}}/orders
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "customerId": "2249262b-6641-4a28-b578-374701066274",
  "firstName": "Hubert",
  "lastName": "Dumas",
  "email": "hubert.dumas@example.com",
  "currency": "AUD",
  "shippingAddress": {
    "addressLine1": "123 Main St",
    "addressLine2": "Apt 4B",
    "city": "Sydney",
    "state": "NSW",
    "postCode": "2000",
    "country": "Australia"
  },
  "Items": [
    {
      "productId": "00d5d543-71a1-4149-ae8b-6695a38d448c",
      "quantity": 2,
      "unitPrice": 89.99
    },
    {
      "productId": "1a308cf3-2bea-45cd-9575-c396db342ad3",
      "quantity": 1,
      "unitPrice": 149.99
    }
  ]
}