@HostAddress=https://localhost:4003
@AccessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMWI1NTBlMC01MjE0LTQ2M2ItODFlZC02MGYyYWIwMGE3MTgiLCJnaXZlbl9uYW1lIjoiSHViZXJ0IiwiZmFtaWx5X25hbWUiOiJEdW1hcyIsImp0aSI6IjZhNDIyMzI0LTcxNjQtNDQwZS1iMDU4LWRkNzNmMDA2MjYyZSIsImV4cCI6MTc1OTIxNzUzOSwiaXNzIjoiaHR0cHM6Ly9nZW1pbmlvcHMuY29tLmF1IiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.1kwEnDy7NRle6QE4g7QiJ6jGKjnVEIq9YmNkLeKegC8

GET {{HostAddress}}/orders?pageNumber=2&pageSize=5

###
GET {{HostAddress}}/orders?pageNumber=2&pageSize=5
Authorization: Bearer {{AccessToken}}

###

POST {{HostAddress}}/orders
Content-Type: application/json

{
  "customerId": "ac2a7b8c-b733-4a3a-850e-039045009288",
  "currency": "AUD",
  "Items": [
    {
      "productId": "00d5d543-71a1-4149-ae8b-6695a38d448c",
      "quantity": 2,
      "unitPrice": 89.99
    },
    {
      "productId": "1a308cf3-2bea-45cd-9575-c396db342ad3",
      "quantity": 1,
      "unitPrice": 149.99
    }
  ]
}